cask_args appdir: "/Applications"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "bat"
brew "diff-so-fancy"
brew "fzf"
brew "gnupg"
brew "hub"
brew "imagemagick"
brew "mysql"
brew "neovim"
brew "ripgrep"
brew "reattach-to-user-namespace"
brew "tldr"
brew "tmux"
brew "yarn"

cask "1password"
cask "1password-cli"
cask "font-fantasque-sans-mono"
cask "google-chrome"
cask "insomnia"
cask "qlcolorcode"
cask "qlstephen"
cask "qlmarkdown"
cask "quicklook-json"
cask "qlimagesize"
cask "skitch"
cask "typora"

