#!/bin/bash

if [ $1 = "branch" ]; then
  git branch -lv | awk '/\[gone\]/ {next} {print}' | fzf | awk '{print $1}' | xargs git checkout
elif [ $1 = "pr" ]; then
  hub pr list | fzf | awk '{print $1}' | sed 's/\#//' | xargs hub pr checkout
else
  echo "Unrecognized option"
  echo "Usage: git pick [branch|pr]"
  exit 1
fi

