"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
continuation_prompt = "[ ](bold bright-black)"
right_format = """$time"""

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$buf\
$nix_shell\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$character
"""

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vimcmd_symbol = ""

[directory]
format = "[$path](bold cyan) "

# NERDFont substitutions

[aws]
symbol = " "
disabled = true

[battery]
full_symbol = "󰁹"
charging_symbol = "󰂄"
discharging_symbol = "󰂃"

[conda]
symbol = " "

[docker_context]
symbol = "󰡨 "
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = " "

[git_status]
diverged = "⇅"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nix_shell]
symbol = " "
format = 'via [$symbol$state(\($name\))]($style) '	

[nodejs]
disabled = true
symbol = " "

[package]
disabled = true
symbol = "󰏗 "

[php]
symbol = " "

[python]
disabled = true
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[time]
disabled = false
style = "dimmed"
format = '[󰅐 $time]($style)'
