#!/usr/bin/env osascript
# Returns the current playing song in Spotify for OSX

set spotify_state to false
set itunes_state to false

if is_app_running("Spotify") then
  tell application "Spotify" to set spotify_state to (player state as text)
end if
if is_app_running("Music") then
  tell application "Music" to set itunes_state to (player state as text)
end if

if spotify_state is equal to "playing" then
  tell application "Spotify"
    set track_name to name of current track
    set artist_name to artist of current track
    return " ♫ " & artist_name & " - " & track_name & " "
  end tell
else if itunes_state is equal to "playing" then
  tell application "Music"
    set track_name to name of current track
    set artist_name to artist of current track
    return " ♫ " & artist_name & " - " & track_name & " "
  end tell
end if

on is_app_running(app_name)
  tell application "System Events" to (name of processes) contains app_name
end is_app_running

