#!/bin/zsh

if [ "$1" != "" ]; then
  host="$1"
else
  host="plindsay-us-central1"
fi

function is_connected() {
  scutil --nc status "$host" | sed -n 1p | grep -q Connected
}

function poll_until_connected() {
  let loops=0 || true
  let max_loops=200 # 200 * 0.1 is 20 seconds. Bash doesn't support floats

  while ! is_connected "$host"; do
    sleep 0.1 # can't use a variable here, bash doesn't have floats
    let loops=$loops+1
    [ $loops -gt $max_loops ] && break
  done

  [ $loops -le $max_loops ]
}

function connect_to_vpn() {
  echo "Connecting"
  scutil --nc start "$host"

  if poll_until_connected "$host"; then
    exit 0
  else
    echo "Error"
    scutil --nc stop "$host"
    exit 1
  fi
}

if is_connected; then
  echo "Disconnecting"
  scutil --nc stop "$host"
else
  connect_to_vpn
fi
