add_newline = false

[character]
symbol = ""
vicmd_symbol = ""

[directory]
prefix = " "

[git_status]
diverged = "⇅"

[nodejs]
disabled = true
symbol = " "

# NERDFont substitutions

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
